name: al_quran_el_karim
description: "A new Flutter project."

publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: '>=3.2.2 <4.0.0'

dependencies:
  arabic_numbers: ^1.0.0
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_localization: ^0.1.14
  go_router: ^12.1.1
  google_fonts: ^6.1.0
  lottie: ^2.7.0
  scrollable_positioned_list: ^0.3.8
  share_plus: ^7.2.1
  shared_preferences: 
  url_launcher: ^6.2.1

dev_dependencies:
  flutter_launcher_icons: "^0.13.1"
  flutter_test:
    sdk: flutter

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "asset/logo/quran.png"
  
  flutter_lints: ^2.0.0

flutter:

  
  uses-material-design: true

 
  assets:
    - asset/animation/
    
 
  fonts:
    - family: quran
      fonts:
        - asset: asset/fonts/HafsSmart_08.ttf
    - family: me_quran
      fonts:
        - asset: asset/fonts/me_quran.ttf
 
flutter_intl:
  enabled: true
